### ISSUE TITLE
Script Issues

### ISSUE THREAD

**Issue by servebeer** [svanhoutte/wyze_garmin_sync#1]
I have a couple of questions about your implementation. First, I am running everything under Ubuntu. My first question is: I f I am using complex characters (i.e. %, ^, etc.) in my wyze password, do I need to enclose them in ""? If I don't, I get errors. Secondly, I am getting this error:

$ ./connect_sync.sh
Traceback (most recent call last):
  File "./scale.py", line 18, in <module>
    print(scale.latest_records)
AttributeError: 'NoneType' object has no attribute 'latest_records'
File is not correct.

I am not exactly sure where this is originating from and how to correct it?

Thanks!
Jon

**Comment by svanhoutte** [comment]
Hello Jon

Thanks for trying it out. I haven't tried the complex characters but will give it a try and fix the protection of the passwords in the scripts. 

Regarding the issue did you install in python the wyze SDK ? And did you update the scale.py with your scale Mac address ?
Could you confirm and post sanitized output of the Mac address script ?

Thanks

**Comment by servebeer** [comment]
I just verified that putting the complex character password in "" works. I also got my other problem fixed. I am running Ubuntu under Windows 11 (I know, sacrilege!) and my editor was messing up my scripts. Got all that resolved and no errors. Now, I just need to wait and see if the data makes it over.

Thanks for taking the time to put this together!

**Comment by servebeer** [comment]
While I'm waiting for it to update, I do notice that the data in "wyze.last.csv" is in kg's event though my Wyze settings are for imperial pounds. Is there a way to correct this?

**Comment by svanhoutte** [comment]
Great news ! For the kg vs lbs my wyze is also in lbs but the way Garmin is expecting it is in kg that s why it is in kg in the script.

**Comment by svanhoutte** [comment]
You don't have to wait for the Cron to run you can just launch the script.

**Comment by servebeer** [comment]
> You don't have to wait for the Cron to run you can just launch the script.

I tried that and then logged into my Garmin Connect Dashboard.  Under Weight, its says "You have no data for this time period."

**Comment by svanhoutte** [comment]
Refresh the browser maybe try to check the 7 days period ? What does the log say. The update is really fast. Like 5 sec max

**Comment by servebeer** [comment]
No joy on refreshing the browser or setting the time range to 7 days. Which log should I look at?

**Comment by svanhoutte** [comment]
If you put it in the Cron like i described it should go in /var/log/syslog. You can grep on garmin and that should give you the logs for the scripts. Otherwise the output in the shell once you launched the script.

**Comment by servebeer** [comment]
So as far as output from the shell goes, when I run "/home/jon/garmin/connect_sync.sh 2>&1 | /usr/bin/logger -t garminsync", there is no output. I just get a prompt (it does take several seconds to run). As far as the crontab syslog message goes... being Ubuntu under Windows, MS has bastardized it some and I can't find those logs anywhere. I'll keep looking.

**Comment by svanhoutte** [comment]
Just try to run this 
home/jon/garmin/connect_sync.sh and show me what comes out.

**Comment by servebeer** [comment]
/home/jon/garmin/connect_sync.sh
File is correct.
./wyze.last.csv: OK
no new measurment

**Comment by svanhoutte** [comment]
Delete the wyze.last.csv and rerun.

**Comment by servebeer** [comment]
File is correct.
md5sum: ./wyze.last.csv: No such file or directory
./wyze.last.csv: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
/home/jon/garmin/connect_sync.sh: line 28: java: command not found
fit file created
2021-12-28 19:58:17,577 [WARNING] File '/home/jon/garmin/wyze.fit' does not exist. Skipping...
Error: No valid files.
file uploaded

**Comment by svanhoutte** [comment]
Do you have java installed ?

**Comment by servebeer** [comment]
Ah Ha! I had to do a touch wyze.fit, delete wyze.last.csv, re-run: connect_sync.sh and then I got this:

File is correct.
md5sum: ./wyze.last.csv: No such file or directory
./wyze.last.csv: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
/home/jon/garmin/connect_sync.sh: line 28: java: command not found
fit file created
2021-12-28 20:02:31,720 [DEBUG] File '/home/jon/garmin/wyze.fit' has extension '.fit'
2021-12-28 20:02:31,721 [DEBUG] File '/home/jon/garmin/wyze.fit' extension '.fit' is valid.
2021-12-28 20:02:31,721 [DEBUG] Using credentials from command line.
2021-12-28 20:02:31,721 [INFO] Try to login on GarminConnect...
2021-12-28 20:02:31,721 [DEBUG] Username: irishjd@gmail.com
2021-12-28 20:02:31,721 [DEBUG] Password: ***************
2021-12-28 20:02:32,099 [DEBUG] Found CSRF token CE18C9148507495D45CD90CE248C8C976182AED8F5CB11747CE9F3858715058847EB3668BB9DE585BE9F4D3BBF226FB9211C
2021-12-28 20:02:33,802 [INFO] Logged in as irishjd@gmail.com
2021-12-28 20:02:33,802 [DEBUG] Login Successful.
2021-12-28 20:02:34,044 [WARNING] Upload failure: Failed to upload wyze.fit
2021-12-28 20:02:34,044 [INFO] All done.
file uploaded

This looks much more promising.

**Comment by servebeer** [comment]
So, that might be usful since we are call a java app (duh). I went ahead and install the jre and re-ran it, but I am still getting the error: [WARNING] Upload failure: Failed to upload wyze.fit

**Comment by servebeer** [comment]
Here is the entire message:

File is correct.
md5sum: ./wyze.last.csv: No such file or directory
./wyze.last.csv: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
FIT CSV Tool - Protocol 2.0 Profile 21.67 Release
Exception in thread "main" java.lang.NullPointerException
        at com.garmin.fit.csv.CSVReader.read(CSVReader.java:56)
        at com.garmin.fit.csv.CSVTool.run(CSVTool.java:249)
        at com.garmin.fit.csv.CSVTool.main(CSVTool.java:362)
fit file created
2021-12-28 20:06:26,028 [DEBUG] File '/home/jon/garmin/wyze.fit' has extension '.fit'
2021-12-28 20:06:26,028 [DEBUG] File '/home/jon/garmin/wyze.fit' extension '.fit' is valid.
2021-12-28 20:06:26,028 [DEBUG] Using credentials from command line.
2021-12-28 20:06:26,028 [INFO] Try to login on GarminConnect...
2021-12-28 20:06:26,028 [DEBUG] Username: irishjd@gmail.com
2021-12-28 20:06:26,028 [DEBUG] Password: ***************
2021-12-28 20:06:26,556 [DEBUG] Found CSRF token 6EFD7BED983C59B063A089E55D0AD51C5DA6B458F2B6C779AD745D5848EFC3DA11E5124726520569BD94B157D8B12D469057
2021-12-28 20:06:29,015 [INFO] Logged in as irishjd@gmail.com
2021-12-28 20:06:29,015 [DEBUG] Login Successful.
2021-12-28 20:06:29,260 [WARNING] Upload failure: Failed to upload wyze.fit
2021-12-28 20:06:29,260 [INFO] All done.
file uploaded

Looks like there are some java issues going on.

**Comment by svanhoutte** [comment]
which version of Java did you install ? 
could you try running java -jar /fitSDKforlder/java/FitCSVTool.jar and see what is the output ? 
I wonder if you need admin right on ubuntu on windows ?

**Comment by servebeer** [comment]
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by servebeer** [comment]
FIT CSV Tool - Protocol 2.0 Profile 21.67 Release
Usage: java -jar FitCSVTool.jar <options> <file>
      -b <FIT FILE> <CSV FILE>  FIT binary to CSV.
      -c <CSV FILE> <FIT FILE>  CSV to FIT binary.
      -t Enable file verification tests.
      -d Enable debug output.
      -i Check integrity of FIT file before decoding.
      -s Show invalid fields in the CSV file.
      -se Show invalid fields in the CSV file as empty cells.
      -u Hide unknown data and report statistics on how much is hidden.
      -x Print byte values as hexadecimal.
      -ex Changes the behaviour of the --defn and --data options to
          filter out the messages listed. The default behaviour without
          this flag is to exclude all messages except those listed
          after the --defn and the --data options.
      -pN Encode file using Protocol Version <N>. Default: 1
      -e Print enum values as their corresponding String labels when
          possible. Note: CSV files generated with this option will not
          be able to be converted back into .FIT files.
      -re Remove expanded fields from CSV output. This removes fields
          that have been generated through component expansion and
          which do not exist in the source .FIT file
      --defn <MESSAGE_STRING_0,MESSAGE_STRING_1,...> Narrows down the
          definitions output to CSV. Use 'none' for no definitions
          When this option is used only the message definitions
          in the comma separated list will be written to the CSV.
          eg. --defn file_capabilities,record,file_creator
          Note: This option is only compatible with the -b option.
      --data <MESSAGE_STRING_0,MESSAGE_STRING_1,...> Narrows down the
          data output to CSV. When this option is used only the data
          in the comma separated list will be written to the csv.
          eg. --data file_capabilities,record,file_creator
          Note: This option is only compatible with the -b option.

**Comment by svanhoutte** [comment]
I think that might be the issue, could you remove it and install openjdk-8-jre.
That s what i m using

**Comment by servebeer** [comment]
I'll give it a shot...

**Comment by svanhoutte** [comment]
i found the issue the repository is missing a file the wyze.csv that is handeling the header. Uploading it right now

**Comment by svanhoutte** [comment]
done

**Comment by servebeer** [comment]
No errors!

File is correct.
./wyze.last.csv: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
FIT CSV Tool - Protocol 2.0 Profile 21.67 Release
./wyze.1.csv encoded into FIT binary file ./wyze.fit.
fit file created
2021-12-28 20:51:34,430 [DEBUG] File '/home/jon/garmin/wyze.fit' has extension '.fit'
2021-12-28 20:51:34,430 [DEBUG] File '/home/jon/garmin/wyze.fit' extension '.fit' is valid.
2021-12-28 20:51:34,431 [DEBUG] Using credentials from command line.
2021-12-28 20:51:34,431 [INFO] Try to login on GarminConnect...
2021-12-28 20:51:34,431 [DEBUG] Username: irishjd@gmail.com
2021-12-28 20:51:34,431 [DEBUG] Password: ***************
2021-12-28 20:51:34,978 [DEBUG] Found CSRF token 1F681A932A48A52BDDECAE64B54AD40A71D6B7E25C7BCEADAF9AF602090610FC3D71E0446E77D2193D71802B60B321A562EA
2021-12-28 20:51:37,113 [INFO] Logged in as irishjd@gmail.com
2021-12-28 20:51:37,113 [DEBUG] Login Successful.
2021-12-28 20:51:37,421 [INFO] Uploaded activity wyze.fit
2021-12-28 20:51:37,421 [INFO] All done.
file uploaded

**Comment by servebeer** [comment]
I now have Wyze scale data in Garmin Connect!

If you ever need help with this project, please let me know. Also, thanks for working this out with me, I really appreciate it!
