### ISSUE TITLE
Issue with authentication with Docker version

### ISSUE THREAD

**Issue by ebressler** [svanhoutte/wyze_garmin_sync#15]
I am getting

```
wyze-garmin-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
wyze-garmin-wyzegarminconnect-1  | Traceback (most recent call last):
wyze-garmin-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 19, in <module>
wyze-garmin-wyzegarminconnect-1  |     response = Client().login(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], key_id=os.environ['WYZE_KEY_ID'],api_key=os.environ['WYZE_API_KEY'])
wyze-garmin-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 184, in login
wyze-garmin-wyzegarminconnect-1  |     response = self._auth_client().user_login(
wyze-garmin-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 88, in user_login
wyze-garmin-wyzegarminconnect-1  |     response = self.api_call(
wyze-garmin-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 58, in api_call
wyze-garmin-wyzegarminconnect-1  |     return super().api_call(
wyze-garmin-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 347, in api_call
wyze-garmin-wyzegarminconnect-1  |     return super().api_call(
wyze-garmin-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 204, in api_call
wyze-garmin-wyzegarminconnect-1  |     return self.do_post(url=api_url, headers=headers, payload=json, params=params)
wyze-garmin-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 132, in do_post
wyze-garmin-wyzegarminconnect-1  |     return self._do_request(client, req)
wyze-garmin-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 106, in _do_request
wyze-garmin-wyzegarminconnect-1  |     raise err
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 93, in _do_request
wyze-garmin-wyzegarminconnect-1  |     response.raise_for_status()
wyze-garmin-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
wyze-garmin-wyzegarminconnect-1  |     raise HTTPError(http_error_msg, response=self)
wyze-garmin-wyzegarminconnect-1  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/api/user/login
wyze-garmin-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
wyze-garmin-wyzegarminconnect-1  | 2023-09-12 16:32:55,297 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
```

Not sure why I am getting a Bad Request here.

**Comment by svanhoutte** [comment]
It looks like you have an issue with your credential, did you get the API ID and API Key from Wyze ?

**Comment by ebressler** [comment]
yes, I did, very odd, I will double check I copied it correctly and I will also just generate another one if needed.

**Comment by svanhoutte** [comment]
did you leave everything in double quotes ? they should be.

**Comment by ebressler** [comment]
yes, I just validated it and I even made a new key and used the new one. odd.

**Comment by ebressler** [comment]
do I need my wyze username and password as well? I was logging into wyze using google, but if I need that, I just have to set a password for that user as well.

**Comment by svanhoutte** [comment]
yes you need wyze login / pass

**Comment by svanhoutte** [comment]
is it working now ?

**Comment by ebressler** [comment]
I couldn't do a password reset most of the day, I got an error from their site. That is fixed now and it gets me farther. Now I have this issue.

```
wyze-garmin-wyzegarminconnect-1  | Scale fund and with MAC WL_SC2_7C78B2FA56DB latest record is
wyze-garmin-wyzegarminconnect-1  | []
wyze-garmin-wyzegarminconnect-1  | Firmware version is 1.0.107
wyze-garmin-wyzegarminconnect-1  | Generating fit data...
wyze-garmin-wyzegarminconnect-1  | Traceback (most recent call last):
wyze-garmin-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 35, in <module>
wyze-garmin-wyzegarminconnect-1  |     fit.write_file_info(time_created=math.trunc(scale.latest_records[0].measure_ts / 1000))
wyze-garmin-wyzegarminconnect-1  |                                                 ~~~~~~~~~~~~~~~~~~~~^^^
wyze-garmin-wyzegarminconnect-1  | IndexError: list index out of range
wyze-garmin-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
wyze-garmin-wyzegarminconnect-1  | 2023-09-13 20:42:51,924 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
wyze-garmin-wyzegarminconnect-1  | Error: No valid files.
wyze-garmin-wyzegarminconnect-1  | file not uploaded
wyze-garmin-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
wyze-garmin-wyzegarminconnect-1  | Scale fund and with MAC WL_SC2_7C78B2FA56DB latest record is
wyze-garmin-wyzegarminconnect-1  | []
wyze-garmin-wyzegarminconnect-1  | Firmware version is 1.0.107
wyze-garmin-wyzegarminconnect-1  | Generating fit data...
wyze-garmin-wyzegarminconnect-1  | Traceback (most recent call last):
wyze-garmin-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 35, in <module>
wyze-garmin-wyzegarminconnect-1  |     fit.write_file_info(time_created=math.trunc(scale.latest_records[0].measure_ts / 1000))
wyze-garmin-wyzegarminconnect-1  |                                                 ~~~~~~~~~~~~~~~~~~~~^^^
wyze-garmin-wyzegarminconnect-1  | IndexError: list index out of range
wyze-garmin-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
wyze-garmin-wyzegarminconnect-1  | 2023-09-13 20:42:51,924 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
wyze-garmin-wyzegarminconnect-1  | Error: No valid files.
wyze-garmin-wyzegarminconnect-1  | file not uploaded
```

Which seems to indicate it is not reading the data from the scale. I have not uploaded in a bit, but there is data there. I may try again after I weigh myself again.

Thanks for you help.

**Comment by ebressler** [comment]
ok, we are closer

```
wyze-garmin-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
wyze-garmin-wyzegarminconnect-1  | Scale fund and with MAC WL_SC2_7C78B2FA56DB latest record is
wyze-garmin-wyzegarminconnect-1  | [<wyze_sdk.ScaleRecord: {'age': 47, 'bmi': 30.3, 'bmr': 1896.0, 'body_fat': 31.8, 'body_vfr': 12, 'body_water': 49.9, 'bone_mineral': 4.3, 'device_id': 'WL_SC2_7C78B2FA56DB', 'family_member_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'height': 185.0, 'id': '2388788071099615026', 'impedance': [529, None, None, None], 'mac': '7C:78:B2:FA:56:DB', 'measure_ts': 1694656650127, 'metabolic_age': 44, 'muscle': 66.2, 'protein': 14.1, 'timezone': 'America/New_York', 'user_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'weight': 228.4}>, <wyze_sdk.ScaleRecord: {'age': 46, 'bmi': 30.4, 'bmr': 1948.0, 'body_fat': 29.8, 'body_vfr': 12, 'body_water': 51.3, 'bone_mineral': 4.5, 'device_id': 'WL_SC2_7C78B2FA56DB', 'family_member_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'height': 185.0, 'id': '7536241075811402674', 'impedance': [410, None, None, None], 'measure_ts': 1694568609039, 'metabolic_age': 43, 'muscle': 68.5, 'protein': 14.5, 'timezone': 'America/New_York', 'user_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'weight': 229.5}>, <wyze_sdk.ScaleRecord: {'age': 46, 'bmi': 29.8, 'bmr': 1935.0, 'body_fat': 29.0, 'body_vfr': 12, 'body_water': 51.9, 'bone_mineral': 4.4, 'device_id': 'WL_SC2_7C78B2FA56DB', 'family_member_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'height': 185.0, 'id': '5564888467972114431', 'impedance': [411, None, None, None], 'measure_ts': 1694396943038, 'metabolic_age': 45, 'muscle': 67.9, 'protein': 14.6, 'timezone': 'America/New_York', 'user_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'weight': 225.1}>, <wyze_sdk.ScaleRecord: {'age': 46, 'bmi': 30.2, 'bmr': 1944.0, 'body_fat': 29.5, 'body_vfr': 12, 'body_water': 51.6, 'bone_mineral': 4.5, 'device_id': 'WL_SC2_7C78B2FA56DB', 'family_member_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'height': 185.0, 'id': '7156483957366735999', 'impedance': [409, None, None, None], 'measure_ts': 1694316313037, 'metabolic_age': 43, 'muscle': 68.3, 'protein': 14.5, 'timezone': 'America/New_York', 'user_id': 'fd605d3eb95b34824cbb998a33a8c36c', 'weight': 228.0}>]
wyze-garmin-wyzegarminconnect-1  | Firmware version is 1.0.107
wyze-garmin-wyzegarminconnect-1  | Generating fit data...
wyze-garmin-wyzegarminconnect-1  | Traceback (most recent call last):
wyze-garmin-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 47, in <module>
wyze-garmin-wyzegarminconnect-1  |     physique_rating=float(scale.latest_records[0].body_type),
wyze-garmin-wyzegarminconnect-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-garmin-wyzegarminconnect-1  | TypeError: float() argument must be a string or a real number, not 'NoneType'
wyze-garmin-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
wyze-garmin-wyzegarminconnect-1  | 2023-09-14 09:51:58,870 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
wyze-garmin-wyzegarminconnect-1  | Error: No valid files.
wyze-garmin-wyzegarminconnect-1  | file not uploaded
```

but `body_type` appears not to exist

**Comment by ebressler** [comment]
here is better formatting of the data for reference
```python
{
    "age": 47,
    "bmi": 30.3,
    "bmr": 1896.0,
    "body_fat": 31.8,
    "body_vfr": 12,
    "body_water": 49.9,
    "bone_mineral": 4.3,
    "device_id": "WL_SC2_7C78B2FA56DB",
    "family_member_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "height": 185.0,
    "id": "2388788071099615026",
    "impedance": [529, None, None, None],
    "mac": "7C:78:B2:FA:56:DB",
    "measure_ts": 1694656650127,
    "metabolic_age": 44,
    "muscle": 66.2,
    "protein": 14.1,
    "timezone": "America/New_York",
    "user_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "weight": 228.4,
}

wyze_sdk.ScaleRecord: {
    "age": 46,
    "bmi": 30.4,
    "bmr": 1948.0,
    "body_fat": 29.8,
    "body_vfr": 12,
    "body_water": 51.3,
    "bone_mineral": 4.5,
    "device_id": "WL_SC2_7C78B2FA56DB",
    "family_member_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "height": 185.0,
    "id": "7536241075811402674",
    "impedance": [410, None, None, None],
    "measure_ts": 1694568609039,
    "metabolic_age": 43,
    "muscle": 68.5,
    "protein": 14.5,
    "timezone": "America/New_York",
    "user_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "weight": 229.5,
}

wyze_sdk.ScaleRecord: {
    "age": 46,
    "bmi": 29.8,
    "bmr": 1935.0,
    "body_fat": 29.0,
    "body_vfr": 12,
    "body_water": 51.9,
    "bone_mineral": 4.4,
    "device_id": "WL_SC2_7C78B2FA56DB",
    "family_member_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "height": 185.0,
    "id": "5564888467972114431",
    "impedance": [411, None, None, None],
    "measure_ts": 1694396943038,
    "metabolic_age": 45,
    "muscle": 67.9,
    "protein": 14.6,
    "timezone": "America/New_York",
    "user_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "weight": 225.1,
}

wyze_sdk.ScaleRecord: {
    "age": 46,
    "bmi": 30.2,
    "bmr": 1944.0,
    "body_fat": 29.5,
    "body_vfr": 12,
    "body_water": 51.6,
    "bone_mineral": 4.5,
    "device_id": "WL_SC2_7C78B2FA56DB",
    "family_member_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "height": 185.0,
    "id": "7156483957366735999",
    "impedance": [409, None, None, None],
    "measure_ts": 1694316313037,
    "metabolic_age": 43,
    "muscle": 68.3,
    "protein": 14.5,
    "timezone": "America/New_York",
    "user_id": "fd605d3eb95b34824cbb998a33a8c36c",
    "weight": 228.0,
}
```

**Comment by svanhoutte** [comment]
Ok i have already that issue in the pipe now for the body type. give me a few days.

**Comment by ebressler** [comment]
sounds good. I altered the file locally and was able to create a `.fit` file that I manually uploaded through the site and it works. So that is the problem. Thanks.

**Comment by svanhoutte** [comment]
Ok i made the changes in the code and the docker image is being reprocessed should be available in the next 30 min

**Comment by svanhoutte** [comment]
Could you pull the latest image and try ?

**Comment by ebressler** [comment]
``` | /wyze_garmin_sync /wyze_garmin_sync
wyze-garmin-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 33
wyze-garmin-wyzegarminconnect-1  |     if scale.latest_records[0].body_type == None:
wyze-garmin-wyzegarminconnect-1  |                                                  ^
wyze-garmin-wyzegarminconnect-1  | IndentationError: unindent does not match any outer indentation level
```

**Comment by ebressler** [comment]
Made a PR to fix https://github.com/svanhoutte/wyze_garmin_sync/pull/17

**Comment by svanhoutte** [comment]
I merged the PR could you please try. I tried on my side it should be working

**Comment by ebressler** [comment]
ok, so, now it works except that I can't get logged into Garmin because it wants 2 step authentication, so it emails or sms's me a code every time it tries to login. Also, I can't turn that off :(. TIme to see if there is another way to login to garmin....

**Comment by svanhoutte** [comment]
The tool i m using gupload doesn't support 2FA. I looked quickly online but can't really find an easy way to make it work.

**Comment by ebressler** [comment]
yeah, we need a mechnism like the API key system wyze uses. Ugh. Garmin is making this a little of a pain.

**Comment by esmoyer** [comment]
> ok, so, now it works except that I can't get logged into Garmin because it wants 2 step authentication, so it emails or sms's me a code every time it tries to login. Also, I can't turn that off :(. TIme to see if there is another way to login to garmin....

Did you check out here: https://www.garmin.com/en-US/account/security/mfa/ looks like you can turn off the toggles. I did that, but now I can't login to test because of too many requests...ugh!

**Comment by ebressler** [comment]
Yes, for me it has `*Permanent two-step verification has been enabled.` below the E-Mail option and it is grey'd out. So I can't disable it. My guess is that since I am new to Garmin, I can't opt out. It seems related to this 

https://support.garmin.com/en-US/?faq=xv3FAPq8hgAwkWnTo6TO98

Probably becuase a I have Garmin Vue 2 plus and it has some data they think needs it.

**Comment by esmoyer** [comment]
> Yes, for me it has `*Permanent two-step verification has been enabled.` below the E-Mail option and it is grey'd out. So I can't disable it. My guess is that since I am new to Garmin, I can't opt out. It seems related to this
> 
> https://support.garmin.com/en-US/?faq=xv3FAPq8hgAwkWnTo6TO98
> 
> Probably becuase a I have Garmin Vue 2 plus and it has some data they think needs it.

Oh lame!

I did try again but get an auth error now too:

```
09/26/2023 9:00:36 PM 2023-09-26 21:00:36,622 [CRITICAL] Login Failure: Expecting value: line 1 column 1 (char 0)
09/26/2023 9:00:36 PM Error: Invalid credentials
09/26/2023 9:00:36 PM file not uploaded
```

**Comment by svanhoutte** [comment]
Ok i found a way to make it work. I just have to polish it a little, i think i could have it up in docker by the end of the weekend. Stay tuned.

**Comment by svanhoutte** [comment]
New image basted on garth is available, be sure to update also your docker compose file and create the tokens repository once you have it run "docker compose run --rm wyzegarminconnect", enter the MFA code. Shutdown the docker and run with "docker compose up -d" . The token is valid for 1 year.

**Comment by svanhoutte** [comment]
@esmoyer could you give it a try and confirm this is working on your side ?

**Comment by esmoyer** [comment]
> @esmoyer could you give it a try and confirm this is working on your side ?

Sorry, I thought I had responded about this working now, I must have imagined it! Yes, it's working now, thanks!

**Comment by svanhoutte** [comment]
fixed and added 2FA support
