### ISSUE TITLE
Was working just stopped recently

### ISSUE THREAD

**Issue by Dunamis8** [svanhoutte/wyze_garmin_sync#18]
Everything was working fine for weeks.  now getting the following.  Any ideas.  I haven't changed any of my passwords, and I don't have 2FA on garmin enabled. Using the legacy script

Fit file wyze_scale.fit created
md5sum: ./cksum.txt: No such file or directory
2023-10-06 14:17:23,087 [DEBUG] File '/home/brent/Documents/wyze_garmin_sync/wyze_scale.fit' has extension '.fit'
2023-10-06 14:17:23,087 [DEBUG] File '/home/brent/Documents/wyze_garmin_sync/wyze_scale.fit' extension '.fit' is valid.
2023-10-06 14:17:23,088 [DEBUG] Using credentials from command line.
2023-10-06 14:17:23,088 [INFO] Try to login on GarminConnect...
2023-10-06 14:17:23,088 [DEBUG] Username: myusername is here
2023-10-06 14:17:23,088 [DEBUG] Password: ***************
2023-10-06 14:17:23,650 [DEBUG] Found CSRF token 
Longtoken here
2023-10-06 14:17:25,120 [CRITICAL] Login Failure: Expecting value: line 1 column 1 (char 0)
Error: Invalid credentials
file not uploaded

**Comment by svanhoutte** [comment]
Hi did you pull the last version ?

**Comment by Dunamis8** [comment]
My bad, just pulled it should have looked at that first.  now getting 


Fit file wyze_scale.fit created
md5sum: ./cksum.txt: No such file or directory
Traceback (most recent call last):
  File "/home/brent/Documents/wyze_garmin_sync/./2FA.py", line 3, in <module>
    import garth
ModuleNotFoundError: No module named 'garth'
file not uploaded

**Comment by svanhoutte** [comment]
which version did you get ?

**Comment by Dunamis8** [comment]
where is your version number?  I just did a git pull to get the latest and then edited the required files again.

**Comment by svanhoutte** [comment]
I just uploaded a fresh version, please try again do a pull and let me know how it goes. Working fine on my end.

**Comment by Dunamis8** [comment]
Odd still getting the below


Fit data generated...
Fit file wyze_scale.fit created
md5sum: ./cksum.txt: No such file or directory
Traceback (most recent call last):
  File "/home/brent/Documents/wyze_garmin_sync/./2FA.py", line 3, in <module>
    import garth
ModuleNotFoundError: No module named 'garth'
file not uploaded

**Comment by svanhoutte** [comment]
you are not using docker ? 
if not try to do a "pip install garth" then relaunch

**Comment by Dunamis8** [comment]
Correct not using docker

doh i should have looked at that.  Progress  not sure why i am getting the md5sum no such file.  I also am not using Garmin 2fa


Fit data generated...
Fit file wyze_scale.fit created
md5sum: ./cksum.txt: No such file or directory
Traceback (most recent call last):
  File "/home/brent/Documents/wyze_garmin_sync/./2FA.py", line 16, in <module>
    email = os.environ['Garmin_username']
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'Garmin_username'
file not uploaded

**Comment by svanhoutte** [comment]
The md5 message is normal. It seems that didn't export the Garmin
credentials.
Do a printer and check if you can see your garmin_username.

**Comment by Dunamis8** [comment]
It was not pulling my username from the connect_sync.legacy.sh file.  If I manually enter my email and password for garmin in the 2FA.py file everything works correctly.
