### ISSUE TITLE
Bad Request for url: https://auth-prod.api.wyze.com/api/user/login

### ISSUE THREAD

**Issue by nicolae-stroncea** [svanhoutte/wyze_garmin_sync#23]
I've filled in all the variables in `docker-compose.yml`

On running 

```
docker compose up -d
docker compose logs -f
```

I get:
```
(env) nicolaestroncea@Nicolaes-Laptop wyze_garmin_sync % docker compose logs -f
wyze_garmin_sync-wyzegarminconnect-1  | Traceback (most recent call last):
wyze_garmin_sync-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 157, in <module>
wyze_garmin_sync-wyzegarminconnect-1  |     main()
wyze_garmin_sync-wyzegarminconnect-1  |     ~~~~^^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 104, in main
wyze_garmin_sync-wyzegarminconnect-1  |     access_token = login_to_wyze()
wyze_garmin_sync-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 20, in login_to_wyze
wyze_garmin_sync-wyzegarminconnect-1  |     response = Client().login(email=WYZE_EMAIL, password=WYZE_PASSWORD, key_id=WYZE_KEY_ID, api_key=WYZE_API_KEY)
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/api/client.py", line 185, in login
wyze_garmin_sync-wyzegarminconnect-1  |     response = self._auth_client().user_login(
wyze_garmin_sync-wyzegarminconnect-1  |         email=self._email,
wyze_garmin_sync-wyzegarminconnect-1  |     ...<3 lines>...
wyze_garmin_sync-wyzegarminconnect-1  |         totp_key=self._totp_key,
wyze_garmin_sync-wyzegarminconnect-1  |     )
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/auth_service.py", line 88, in user_login
wyze_garmin_sync-wyzegarminconnect-1  |     response = self.api_call(
wyze_garmin_sync-wyzegarminconnect-1  |         '/api/user/login', json=kwargs, request_specific_headers=api_headers, nonce=nonce
wyze_garmin_sync-wyzegarminconnect-1  |     )
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/auth_service.py", line 58, in api_call
wyze_garmin_sync-wyzegarminconnect-1  |     return super().api_call(
wyze_garmin_sync-wyzegarminconnect-1  |            ~~~~~~~~~~~~~~~~^
wyze_garmin_sync-wyzegarminconnect-1  |         api_method,
wyze_garmin_sync-wyzegarminconnect-1  |         ^^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |     ...<4 lines>...
wyze_garmin_sync-wyzegarminconnect-1  |         nonce=nonce,
wyze_garmin_sync-wyzegarminconnect-1  |         ^^^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |     )
wyze_garmin_sync-wyzegarminconnect-1  |     ^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/base.py", line 347, in api_call
wyze_garmin_sync-wyzegarminconnect-1  |     return super().api_call(
wyze_garmin_sync-wyzegarminconnect-1  |            ~~~~~~~~~~~~~~~~^
wyze_garmin_sync-wyzegarminconnect-1  |         api_method,
wyze_garmin_sync-wyzegarminconnect-1  |         ^^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |     ...<5 lines>...
wyze_garmin_sync-wyzegarminconnect-1  |         auth=None,
wyze_garmin_sync-wyzegarminconnect-1  |         ^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |     )
wyze_garmin_sync-wyzegarminconnect-1  |     ^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/base.py", line 204, in api_call
wyze_garmin_sync-wyzegarminconnect-1  |     return self.do_post(url=api_url, headers=headers, payload=json, params=params, method=http_verb)
wyze_garmin_sync-wyzegarminconnect-1  |            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/base.py", line 132, in do_post
wyze_garmin_sync-wyzegarminconnect-1  |     return self._do_request(client, req)
wyze_garmin_sync-wyzegarminconnect-1  |            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/base.py", line 106, in _do_request
wyze_garmin_sync-wyzegarminconnect-1  |     raise err
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/service/base.py", line 93, in _do_request
wyze_garmin_sync-wyzegarminconnect-1  |     response.raise_for_status()
wyze_garmin_sync-wyzegarminconnect-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~^^
wyze_garmin_sync-wyzegarminconnect-1  |   File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
wyze_garmin_sync-wyzegarminconnect-1  |     raise HTTPError(http_error_msg, response=self)
wyze_garmin_sync-wyzegarminconnect-1  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/api/user/login
wyze_garmin_sync-wyzegarminconnect-1  | crond[14]: crond (busybox 1.36.1) started, log level 8
```

Any ideas why this might be happening?

System: Apple M1 Max

**Comment by svanhoutte** [comment]
Hi 
The script will try to save the token locally on your device, has the docker user write access in the directory ?

**Comment by nicolae-stroncea** [comment]
I've done the following:
```
sudo chmod -R 777 wyze_garmin_sync
drwxrwxrwx@ 15 user  staff   480  8 Nov 22:56 wyze_garmin_sync
```

and looks like I'm still encountering the same issue :/

**Comment by svanhoutte** [comment]
did you get the keys from  https://developer-api-console.wyze.com/#/apikey/view ? and updated the docker compose file accordingly ? 
Can you get in the docker and try creating a file in the folder /wyze_garmin_sync/tokens : 
docker exec -it (container id) sh
then cd /wyze_garmin_sync/tokens 
then touch test

**Comment by svanhoutte** [comment]
@nicolae-stroncea any update ?

**Comment by nicolae-stroncea** [comment]
Haven't been able to try this yet. Will try over next 1-2 weeks and get back to you!

**Comment by avoev** [comment]
Got the same error, the issue appears to be that the token has expired (even though it is supposed to the good for a year). Re-created and updated the Key Id and Api Key from https://developer-api-console.wyze.com and everything is back to normal.

**Comment by svanhoutte** [comment]
Key Id and Api Key recreated and back to normal behavior.
