### ISSUE TITLE
TOTP question

### ISSUE THREAD

**Issue by papakpmartin** [svanhoutte/wyze_garmin_sync#5]
This probably isn't really an issue, but I'm getting the following in the logging:

```
/wyze_garmin_sync /wyze_garmin_sync
Traceback (most recent call last):
  File "/wyze_garmin_sync/scale.py", line 17, in <module>
    client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], totp_key=os.environ['WYZE_TOTP'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 66, in __init__
    self.login()
  File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 164, in login
    response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 83, in user_login
    verification_code = totp(totp_key)
                        ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mintotp.py", line 20, in totp
    return hotp(key, int(time.time() / time_step), digits, digest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mintotp.py", line 11, in hotp
    key = base64.b32decode(key.upper() + '=' * ((8 - len(key)) % 8))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/base64.py", line 254, in b32decode
    return _b32decode(_b32alphabet, s, casefold, map01)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/base64.py", line 236, in _b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
2023-02-04 13:29:46,106 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
Error: No valid files.
file not uploaded
```

I assume I have the Wyze 2FA set up incorrectly, but I'm not sure how.

I set up a fresh "Two-Factor Authentication" in the Wyze app (and it's working). I _think_ I saved the right thing from "Step 3", which basically looks like a UUID. I entered that UUID as the `WYZE_TOTP` (using the Docker Compose file).

Was that the wrong thing to be using?

**Comment by papakpmartin** [comment]
Solved. It was supposed to be the ~16 character code that you get before you get the UUID.

This project is a cool idea! I can't wait to see how it works.
